#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 25 20:11:42 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=rethinking-voxels_r0.1-beta9 + Clrwl_1.0.5.zip
enableShaders=false
